begin;

insert into public.exercises (
  id,
  name,
  slug,
  is_active,
  muscle_groups,
  secondary_muscles,
  equipment,
  category,
  mechanic,
  force,
  difficulty,
  tracking_type,
  progression_model,
  default_sets,
  default_reps,
  rep_range_min,
  rep_range_max,
  increment_lbs,
  is_bodyweight,
  is_unilateral,
  beginner_starting_weight_lbs,
  progressive_overload_notes,
  instructions,
  cues,
  common_mistakes,
  media_url,
  media_type,
  thumbnail_url,
  secondary_media_urls
)
values
  (
    '2f93f3d9-2e20-4f8a-af71-c3ab95a71cb4'::uuid,
    'Dumbbell Bench Press',
    'dumbbell-bench-press',
    true,
    array['chest']::text[],
    array['triceps','shoulders']::text[],
    array['dumbbell','bench']::text[],
    'compound',
    'push',
    'push',
    'beginner',
    'weight_reps',
    'linear',
    3,
    8,
    6,
    12,
    5.00,
    false,
    false,
    20.00,
    'Increase weight when all sets reach the top of the rep range with control.',
    array[
      '1. Sit on a bench with dumbbells resting on your thighs.',
      '2. Lie back and bring the dumbbells to chest level.',
      '3. Press the weights up until arms are fully extended.',
      '4. Lower under control to chest level.',
      '5. Repeat for all reps.'
    ]::text[],
    array['press evenly','control the descent','feet planted']::text[],
    array[
      'Letting dumbbells drift unevenly - keep both sides controlled.',
      'Dropping too fast - lower with control.',
      'Arching excessively - keep a stable base.'
    ]::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    '4a3f6a2e-b301-4bc2-9fcb-7c8dcae91f31'::uuid,
    'Barbell Bent Over Row',
    'barbell-bent-over-row',
    true,
    array['back']::text[],
    array['biceps','forearms']::text[],
    array['barbell']::text[],
    'compound',
    'pull',
    'pull',
    'intermediate',
    'weight_reps',
    'linear',
    3,
    8,
    6,
    12,
    5.00,
    false,
    false,
    65.00,
    'Add weight once all sets are completed at the top rep range with good form.',
    array[
      '1. Hold a barbell with a shoulder-width grip.',
      '2. Hinge at the hips with a flat back.',
      '3. Pull the bar toward your lower chest.',
      '4. Squeeze your back at the top.',
      '5. Lower under control.'
    ]::text[],
    array['flat back','pull elbows back','brace core']::text[],
    array[
      'Rounding the back - keep spine neutral.',
      'Using momentum - control each rep.',
      'Standing too upright - maintain hinge.'
    ]::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    'f78af43d-5bda-49bd-a2e3-7646e6fe9a8f'::uuid,
    'Barbell Upright Row',
    'barbell-upright-row',
    true,
    array['shoulders']::text[],
    array['traps']::text[],
    array['barbell']::text[],
    'compound',
    'pull',
    'pull',
    'beginner',
    'weight_reps',
    'linear',
    3,
    10,
    8,
    12,
    5.00,
    false,
    false,
    45.00,
    'Increase weight once all sets reach the top rep range with clean form.',
    array[
      '1. Hold a barbell with a narrow grip.',
      '2. Pull the bar straight up toward your chest.',
      '3. Lead with your elbows.',
      '4. Keep the bar close to your body.',
      '5. Lower under control.'
    ]::text[],
    array['elbows high','bar close','control the movement']::text[],
    array[
      'Pulling with wrists - lead with elbows.',
      'Lifting too heavy - reduces control.',
      'Shrugging excessively - focus on shoulders.'
    ]::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    'e589cf5d-204e-41e5-a141-64d1ba5f3f17'::uuid,
    'Plate-Loaded Hack Squat',
    'plate-loaded-hack-squat',
    true,
    array['quads']::text[],
    array['glutes']::text[],
    array['machine']::text[],
    'compound',
    'squat',
    'push',
    'intermediate',
    'weight_reps',
    'linear',
    3,
    10,
    8,
    12,
    5.00,
    false,
    false,
    90.00,
    'Increase weight once full depth reps are achieved across all sets.',
    array[
      '1. Position shoulders under pads and feet on platform.',
      '2. Lower into a squat by bending knees.',
      '3. Keep your back pressed against the pad.',
      '4. Drive through your heels to stand.',
      '5. Repeat under control.'
    ]::text[],
    array['push through heels','knees track forward','stay tight']::text[],
    array[
      'Letting knees cave in - push them outward.',
      'Partial range of motion - go deeper.',
      'Locking knees aggressively - control the top.'
    ]::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    '8dd6f96c-b950-469f-b588-5f2f2378ce42'::uuid,
    'Plate-Loaded Preacher Curl',
    'plate-loaded-preacher-curl',
    true,
    array['biceps']::text[],
    array['forearms']::text[],
    array['machine']::text[],
    'isolation',
    'pull',
    'pull',
    'beginner',
    'weight_reps',
    'double_progression',
    3,
    10,
    8,
    12,
    5.00,
    false,
    false,
    20.00,
    'Increase weight once all sets reach the top rep range with strict form.',
    array[
      '1. Sit with arms resting on the preacher pad.',
      '2. Grip handles or bar.',
      '3. Curl upward while keeping upper arms fixed.',
      '4. Squeeze at the top.',
      '5. Lower slowly.'
    ]::text[],
    array['slow negative','full stretch','no swinging']::text[],
    array[
      'Using momentum - keep movement strict.',
      'Lifting elbows - keep them planted.',
      'Partial reps - use full range.'
    ]::text[],
    null,
    'none',
    null,
    '{}'::text[]
  )
on conflict (slug) do update
set
  name = excluded.name,
  is_active = excluded.is_active,
  muscle_groups = excluded.muscle_groups,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  category = excluded.category,
  mechanic = excluded.mechanic,
  force = excluded.force,
  difficulty = excluded.difficulty,
  tracking_type = excluded.tracking_type,
  progression_model = excluded.progression_model,
  default_sets = excluded.default_sets,
  default_reps = excluded.default_reps,
  rep_range_min = excluded.rep_range_min,
  rep_range_max = excluded.rep_range_max,
  increment_lbs = excluded.increment_lbs,
  is_bodyweight = excluded.is_bodyweight,
  is_unilateral = excluded.is_unilateral,
  beginner_starting_weight_lbs = excluded.beginner_starting_weight_lbs,
  progressive_overload_notes = excluded.progressive_overload_notes,
  instructions = excluded.instructions,
  cues = excluded.cues,
  common_mistakes = excluded.common_mistakes,
  media_url = excluded.media_url,
  media_type = excluded.media_type,
  thumbnail_url = excluded.thumbnail_url,
  secondary_media_urls = excluded.secondary_media_urls;

commit;
