begin;

insert into public.exercises (
  id,
  name,
  slug,
  is_active,
  muscle_groups,
  secondary_muscles,
  equipment,
  category,
  mechanic,
  force,
  difficulty,
  tracking_type,
  progression_model,
  default_sets,
  default_reps,
  rep_range_min,
  rep_range_max,
  increment_lbs,
  is_bodyweight,
  is_unilateral,
  beginner_starting_weight_lbs,
  progressive_overload_notes,
  instructions,
  cues,
  common_mistakes,
  media_url,
  media_type,
  thumbnail_url,
  secondary_media_urls
)
values
  (
    '7d2df8f8-8b3d-4e58-9f5e-1bcbecf6b1a1'::uuid,
    'Bench Press',
    'bench-press',
    true,
    array['chest','shoulders','triceps']::text[],
    array['core']::text[],
    array['barbell','bench']::text[],
    'compound',
    'push',
    'push',
    'intermediate',
    'weight_reps',
    'double_progression',
    3,
    10,
    6,
    12,
    5.00,
    false,
    false,
    45.00,
    'Increase load by 5 lbs when all working sets hit rep target with stable form.',
    array['Plant feet and brace core before unrack.', 'Lower bar with control to mid chest and press to lockout.']::text[],
    array['Keep shoulder blades retracted.', 'Drive through the floor for stability.']::text[],
    array['Bouncing the bar off the chest.', 'Losing upper-back tightness at the bottom.']::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    '27f540f1-15a6-46ee-8ad8-8b3bdac75cc2'::uuid,
    'Pull Up',
    'pull-up',
    true,
    array['back','biceps']::text[],
    array['forearms','core']::text[],
    array['bodyweight','pullup_bar']::text[],
    'compound',
    'pull',
    'pull',
    'intermediate',
    'bodyweight_reps',
    'double_progression',
    3,
    8,
    6,
    12,
    2.50,
    true,
    false,
    null,
    'Add small load once all sets reach the top of range with full hang reps.',
    array['Start from a dead hang each rep.', 'Pull chest toward the bar and control the descent.']::text[],
    array['Keep ribs down and avoid excessive swinging.']::text[],
    array['Using momentum instead of controlled pulling.', 'Partial range reps with no full extension.']::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    '4192fe9a-5416-4648-bf8c-c21e58ec8f89'::uuid,
    'Bicep Curl',
    'bicep-curl',
    true,
    array['biceps']::text[],
    array['forearms']::text[],
    array['cable']::text[],
    'isolation',
    'pull',
    'pull',
    'beginner',
    'weight_reps',
    'double_progression',
    3,
    12,
    8,
    15,
    5.00,
    false,
    false,
    20.00,
    'Progress load once you can complete all sets without shoulder swing.',
    array['Keep elbows pinned to your sides.', 'Control both curl and lowering phases.']::text[],
    array['Squeeze at the top without shrugging.']::text[],
    array['Leaning back to move more weight.', 'Letting elbows drift forward.']::text[],
    null,
    'none',
    null,
    '{}'::text[]
  ),
  (
    'f26f8f53-fd7a-4d0f-bca9-c46c2e741b8c'::uuid,
    'Tricep Pushdown',
    'tricep-pushdown',
    true,
    array['triceps']::text[],
    array['shoulders']::text[],
    array['cable']::text[],
    'isolation',
    'push',
    'push',
    'beginner',
    'weight_reps',
    'double_progression',
    3,
    12,
    8,
    15,
    5.00,
    false,
    false,
    20.00,
    'Increase load after all sets are completed with full elbow extension and control.',
    array['Keep elbows tucked and shoulders down.', 'Press to full extension, then return under control.']::text[],
    array['Lock in torso position to avoid momentum.']::text[],
    array['Flaring elbows excessively.', 'Turning pushdown into a bodyweight dip pattern.']::text[],
    null,
    'none',
    null,
    '{}'::text[]
  )
on conflict (slug) do update
set
  name = excluded.name,
  is_active = excluded.is_active,
  muscle_groups = excluded.muscle_groups,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  category = excluded.category,
  mechanic = excluded.mechanic,
  force = excluded.force,
  difficulty = excluded.difficulty,
  tracking_type = excluded.tracking_type,
  progression_model = excluded.progression_model,
  default_sets = excluded.default_sets,
  default_reps = excluded.default_reps,
  rep_range_min = excluded.rep_range_min,
  rep_range_max = excluded.rep_range_max,
  increment_lbs = excluded.increment_lbs,
  is_bodyweight = excluded.is_bodyweight,
  is_unilateral = excluded.is_unilateral,
  beginner_starting_weight_lbs = excluded.beginner_starting_weight_lbs,
  progressive_overload_notes = excluded.progressive_overload_notes,
  instructions = excluded.instructions,
  cues = excluded.cues,
  common_mistakes = excluded.common_mistakes,
  media_url = excluded.media_url,
  media_type = excluded.media_type,
  thumbnail_url = excluded.thumbnail_url,
  secondary_media_urls = excluded.secondary_media_urls;

commit;
